<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    
    protected $fillable = [
        
        'sender',
        'receiver',
        'po_number',
        'release_number',
        'po_date',
        'terms_info',
        'fob_info',
        'ship_to_name',
        'ship_to_address1',
        'ship_to_address2',
        'ship_to_location',
        'ship_to_city',
        'ship_to_state',
        'ship_to_postal',
        'ship_to_country',
        'ship_to_contact',
        'bill_to_name',
        'bill_to_address1',
        'bill_to_address2',
        'bill_to_location',
        'bill_to_city',
        'bill_to_state',
        'bill_to_postal',
        'bill_to_country',
        'bill_to_contact',
        'hdr_user_defined_field1',
        'hdr_user_defined_field2',
        'hdr_user_defined_field3',
        'hdr_user_defined_field4',
        'hdr_user_defined_field5',
        'hdr_user_defined_field6',
        'hdr_user_defined_field7',
        'hdr_user_defined_field8',
        'hdr_user_defined_field9',
        'hdr_user_defined_field10',
        'hdr_user_defined_field11',
        'hdr_user_defined_field12',
        'hdr_user_defined_field13',
        'hdr_user_defined_field14',
        'hdr_user_defined_field15',
        'hdr_user_defined_field16',
        'hdr_user_defined_field17',
        'hdr_user_defined_field18',
        'hdr_user_defined_field19',
        'hdr_user_defined_field20',
        'notes',
        'line_nbr',
        'supplier_item_nbr',
        'item_description',
        'quantity',
        'unit_price',
        'uom_basis_of_uom',
        'buyer_item_nbr',
        'manufacturer_item_nbr',
        'dtl_user_defined_field1',
        'dtl_user_defined_field2',
        'dtl_user_defined_field3',
        'dtl_user_defined_field4',
        'dtl_user_defined_field5',
        'dtl_user_defined_field6',
        'dtl_user_defined_field7',
        'dtl_user_defined_field8',
        'dtl_user_defined_field9',
        'dtl_user_defined_field10',
        'dtl_user_defined_field11',
        'dtl_user_defined_field12',
        'dtl_user_defined_field13',
        'dtl_user_defined_field14',
        'dtl_user_defined_field15',
        'dtl_user_defined_field16',
        'dtl_user_defined_field17',
        'dtl_user_defined_field18',
        'dtl_user_defined_field19',
        'dtl_user_defined_field20',
        'po_purpose',
        'sac_info',
        'delivery_date_requested',
        'last_delivery_date_requested',
        'sub_line_item',
        'item_info'
        
    ];
}
